// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {aircracker} from '../models';

export function GetInterfaces():Promise<Array<aircracker.Interface>>;

export function GetServices():Promise<Array<aircracker.NetSvc>>;
