// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInterfaces() {
  return window['go']['aircracker']['App']['GetInterfaces']();
}

export function GetServices() {
  return window['go']['aircracker']['App']['GetServices']();
}
